version: '3'
services:
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=PUID
      - PGID=PGID
      - TZ=timezone
    volumes:
      - /path/to/grocy:/config
    ports:
      - 80:80
    restart: unless-stopped    
