version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - PUID=PUID
      - PGID=PGID
      - TZ=timezone  
    volumes:
      - /path/to/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always  
