version: '3'
services:
  cloudcmd:
    image: coderaiser/cloudcmd
    container_name: cloudcmd
    ports:
      - 8000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    restart: unless-stopped   
