version: '3'
services:
  joplin-db:
    image: postgres:15
    container_name: joplin-db
    volumes:
      - /path/to/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=joplin
  
  joplin:
    image: joplin/server:latest
    container_name: joplin-server
    depends_on:
      - joplin-db
    ports:
      - 22300:22300
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=https://subdomain.websiteurl.com
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=db_user
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=joplin-db
      - MAILER_ENABLED=1
      - MAILER_HOST=smtp.gmail.com
      - MAILER_PORT=465
      - MAILER_SECURE=1
      - MAILER_AUTH_USER=youremail@gmail.com
      - MAILER_AUTH_PASSWORD=Y0urP@ssw0rd
      - MAILER_NOREPLY_NAME=Joplin
      - MAILER_NOREPLY_EMAIL=email@email.com